#!/usr/bin/env bash
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times


IP="${1}"
fn=$(basename $0)

if [ "$IP" ]
then
    ping -c 5 "$IP"
else
    echo "Usage: $fn {IP_ADDRESS}"
fi