#!/usr/bin/env bash
# While Loop: Iterate from 1 ... 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# otherwise, displays the number

number=1

while [ $number -le 100 ]
do
    if (( number % 3 == 0 && number % 5 == 0))
    then
        echo "FizzBuzz"
    elif (( number % 3 == 0 ))
    then
        echo "Fizz"
    elif (( number % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$number"

    fi
    (( number++ ))
done