#!/usr/bin/env bash
#Using Case Statement
# display hours from 0 to 12
# display minutes form 1 to 59

hour=0
minutes=0

while [ $hour -le 2 ]
do
    echo "Hour: $hour"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    (( hour++ ))
done