#!/usr/bin/env bash
# Checking and reading through a file named "School"
#   if the file exists: school file exists
#       if the file is empty: school file is empty
#       if the file is not empty: school file is not empty
#       if the file is a regular file: school is a regular file
#       if the file is not a regular file: (nothing)
#   if the file does not exist: school file does not exist
list=$(ls)

if [ -e "school" ]
then
    echo "school file exists"

    if [ -s "school" ]
    then 
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    if [ -f "school" ]
    then 
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi